### ISSUE TITLE
[Symfony 4.4][Security] AuthorizationChecker::isGranted() and ListenerInterface not detected

### ISSUE THREAD

**Issue by Herimamitiana** [rectorphp/rector-symfony#106]
Running Rector with SF 4.4 as target, it doesn't look like it is detecting the deprecation for [this change](https://github.com/symfony/symfony/blob/4.4/UPGRADE-4.4.md#security)

> Deprecated passing more than one attribute to AccessDecisionManager::decide() and AuthorizationChecker::isGranted() (and indirectly the is_granted() Twig and ExpressionLanguage function)

    declare(strict_types=1);

    use Rector\Core\Configuration\Option;
    use Rector\Symfony\Set\SymfonyLevelSetList;
    use Rector\Core\ValueObject\PhpVersion;
    use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;
    
    return static function (ContainerConfigurator $containerConfigurator): void {
        // get parameters
        $parameters = $containerConfigurator->parameters();
        $parameters->set(Option::BOOTSTRAP_FILES, [
            __DIR__ . '/vendor/autoload.php',
            __DIR__ . '/bin/.phpunit/phpunit-6.5/vendor/autoload.php',
        ]);
        $parameters->set(
            Option::PHP_VERSION_FEATURES,
            PhpVersion::PHP_74
        );
        $parameters->set(
            Option::SYMFONY_CONTAINER_XML_PATH_PARAMETER,
            __DIR__ . '/var/cache/dev/App_KernelDevDebugContainer.xml'
        );
    
        $containerConfigurator->import(SymfonyLevelSetList::UP_TO_SYMFONY_44);
    };

File analyzed with   `vendor/bin/rector process src/App/Service/FooService --dry-run`
        

    namespace App\Service;
      
    use Symfony\Component\Security\Guard\AuthenticatorInterface;
    use Symfony\Component\Security\Http\Firewall\ListenerInterface;
      
    class FooService
    {
    
        
        /** @var AuthorizationCheckerInterface */
        private $auth;
        /** @var ListenerInterface */
        private $listener;
    
        public function __construct(
            AuthorizationCheckerInterface $auth,
            ListenerInterface $listener
        ) {
            $this->auth= $auth;
            $this->listener= $listener;
        }
        
        public function foo() {
            if ($this->auth->isGranted(['ROLE_USER', 'ROLE_ADMIN'])) {
                die();
            }
       }
    }

The Rule set for [Symfony 4.4](https://github.com/rectorphp/rector-symfony/blob/main/config/sets/symfony/symfony44.php) seems to only include elements concerning the console and [nothing else](https://github.com/symfony/symfony/blob/4.4/UPGRADE-4.4.md)

I suspect I might have missed something of misused/misconfigured the script but wanted to open an Issue to be sure.

**Comment by TomasVotruba** [comment]
Hi, the framework sets are not 100 % complete, as they're build as the open-source community voluntarily contributes the rules. Each project is different, so each what might be enough for some, might be missed feature for another.

Could you provide the minimal diff of the change you expect? E.g.

```diff
-$value
+$another
```
