### ISSUE TITLE
Symfony Userinterface::getUsername => getUserIdentifier only for Symfony >= 6.0

### ISSUE THREAD

**Issue by mkrauser** [rectorphp/rector-symfony#112]
Symfony changes the name getUsername in the UserInterface to getUserIdentifier with Symfony 6.0.

Using the new name works starting at Symfony 5.3, but since the UserInterface is not changed yet, renaming the method in Symfony 5.3 and 5.4 will break the code, since the User-Class implementing the Interface is missing getUsername()

This Rule should be moved to the Symfony 6.0 set.

see 
https://github.com/symfony/symfony/blob/5.3/src/Symfony/Component/Security/Core/User/UserInterface.php
https://github.com/rectorphp/rector-symfony/blob/8aa9a6b20bdbc9859cdd82f03aa975572cc35eb0/config/sets/symfony/symfony53.php#L41

**Comment by mkrauser** [comment]
Sure, here it is

**Comment by samsonasik** [comment]
Fixed at https://github.com/rectorphp/rector-symfony/pull/113
