### ISSUE TITLE
Less dependencies

### ISSUE THREAD

**Issue by seb-jean** [rectorphp/rector-symfony#12]
Hello,
Congratulations on your work on Rector.
Is it possible for rector-symfony to have less dependencies (or even 0 dependencies) like Rector?
Thanks

**Comment by TomasVotruba** [comment]
Hi, thank you :+1: 

Currently the rector-symfony is part of rector/rector, so it has no dependencies at all.
In the future we plan to separate them, but keep the independence.

**Comment by mente** [comment]
I've just by accident stumbled upon this as a bug. Being under the assumption that since rector/rector 0.11 you still have to install additional rules on demand. Might make sense to make `rector/rector` 0.11 conflict with `rector/rector-symfony`, `rector/rector-phpunit`, etc.?

**Comment by TomasVotruba** [comment]
> Might make sense to make rector/rector 0.11 conflict with rector/rector-symfony, rector/rector-phpunit, etc.?

You're right, that would make sense in this case :+1: 

Could you send PR?

**Comment by mente** [comment]
With pleasure. But where is rector/rector composer.json is stored? https://github.com/rectorphp/rector-src/blob/main/build/target-repository/composer.json ?

**Comment by TomasVotruba** [comment]
@mente Yes, that's the one :+1:
