### ISSUE TITLE
Rector doesn't complain about missing XML container missing

### ISSUE THREAD

**Issue by vasilvestre** [rectorphp/rector-symfony#122]
I had to modify xml path option to get rector working on some rules. I'm quite surprised that it didn't complain about it.

Is it a wanted behaviour ?

**Comment by samsonasik** [comment]
could you create minimal reproducible repository for it with rector config with invalid xml? I tried in unit tests, and it seems expected show error:

```
Symfony\Component\Filesystem\Exception\IOException: Failed to read "/Users/samsonasik/www/rector-symfony/tests/Rector/MethodCall/ContainerGetToConstructorInjectionRector/config/../xml/services_not_exists.xml" file: "Failed to open stream: No such file or directory"
```

**Comment by vasilvestre** [comment]
> could you create minimal reproducible repository for it with rector config with invalid xml? I tried in unit tests, and it seems expected show error:
> 
> ```
> Symfony\Component\Filesystem\Exception\IOException: Failed to read "/Users/samsonasik/www/rector-symfony/tests/Rector/MethodCall/ContainerGetToConstructorInjectionRector/config/../xml/services_not_exists.xml" file: "Failed to open stream: No such file or directory"
> ```

I will try this. My project is big so I don't know if I can reproduce it in a new project.

**Comment by samsonasik** [comment]
Ok, I am closing it, feel free to provide a sample repository when you can.
