### ISSUE TITLE
Rector failed on default Symfony config run if PHPUnit is not installed.

### ISSUE THREAD

**Issue by bocharsky-bw** [rectorphp/rector-symfony#123]
See "Class PHPUnit\Framework\TestCase not found." error in the output:
```
$ ./vendor/bin/rector process src/


 [WARNING] Your project requires min PHP version "7.4".

           1 Rector rules defined in your configuration require higher PHP version and will not run,
           to avoid breaking your codebase, use -vvv for detailed info.


 ! [NOTE] Do you want to run them? Make "require" > "php" in `composer.json` higher,
 !        or add "Option::PHP_VERSION_FEATURES" parameter to your `rector.php`.


In RuntimeReflectionProvider.php line 185:

  Class PHPUnit\Framework\TestCase not found.


process [-n|--dry-run] [-a|--autoload-file AUTOLOAD-FILE] [--no-progress-bar] [--no-diffs] [--output-format OUTPUT-FORMAT] [--memory-limit MEMORY-LIMIT] [--clear-cache] [--port PORT] [--identifier IDENTIFIER] [--] [<source>...]
```

Just for the reference, my `rector.php` config is:
```
return static function (ContainerConfigurator $containerConfigurator): void {
    // region Symfony Container
    $parameters = $containerConfigurator->parameters();
    $parameters->set(
        Option::SYMFONY_CONTAINER_XML_PATH_PARAMETER,
        __DIR__ . '/var/cache/dev/App_KernelDevDebugContainer.xml'
    );
    // endregion

    $containerConfigurator->import(SymfonyLevelSetList::UP_TO_SYMFONY_54);
    $containerConfigurator->import(SymfonySetList::SYMFONY_CODE_QUALITY);
    $containerConfigurator->import(SymfonySetList::SYMFONY_CONSTRUCTOR_INJECTION);
};
```

Installing PHPUnit is a workaround for this.

**Comment by TomasVotruba** [comment]
Hi, if some rule is working with PHPUnit, it will require it's dependency, so this behavior is expected.

Could you share the demo link that shows this error? https://getrector.org/demo

**Comment by bocharsky-bw** [comment]
I'm not sure if it's possible to do with that https://getrector.org/demo feature as I'm talking about the whole Symfony project... I was trying to apply the default Symfony config there but it shows this error:

> Failed to read "/var/www/var/demo/15y7lp7hy5ju1otiox9a/var/cache/dev/App_Ke
rnelDevDebugContainer.xml" file: ""

You can see it here: https://getrector.org/demo/724dbe74-72d5-49b1-adb9-5cbf63a18006

Anyway, I created a reproducer based on the whole Symfony Demo project where I just dropped all the PHPUnit tests and the PHPUnit Compoer dependency. So, that project is literally has no PHPUnit, and you can see the error I mentioned in the PR description by running `./vendor/bin/rector process src` there.

See https://github.com/bocharsky-bw/no-phpunit-rector-reproducer

**Comment by bocharsky-bw** [comment]
> Hi, if some rule is working with PHPUnit, it will require it's dependency, so this behavior is expected.

If it's expected behavior - this sounds weird to me. I suppose that `rector/rector-symfony` should require `phpunit/phpunit` as the main dependency at least. Otherwise, that rule should be skipped if no PHPUnit installed in the project, i.e. when PHPUnit class isn't available IMO

**Comment by TomasVotruba** [comment]
> Anyway, I created a reproducer based on the whole Symfony Demo project where I just dropped all the PHPUnit tests and the PHPUnit Compoer dependency

That's very hepful. Could you add failing Rector CI action so we see exactly the steps to reproduce?

**Comment by TomasVotruba** [comment]
> If it's expected behavior - this sounds weird to me. I suppose that rector/rector-symfony should require phpunit/phpunit as the main dependency at least. 

That might be optional or forced dependency.  Both might conflict with user's project depenendencies, that we try to isolate from.
Which rule exactly is causing it?

**Comment by TomasVotruba** [comment]
See for duplicated issue solution https://github.com/rectorphp/rector/issues/6531#issuecomment-870586660
