### ISSUE TITLE
[Question] Symfony 4.4 to 5.4 with a lot of vendors

### ISSUE THREAD

**Issue by Garfield-fr** [rectorphp/rector-symfony#137]
Hi,

I have to update a project running on Symfony 4.4 to version 5.4. This project has a lot of libraries and bundles and I'm having trouble synchronizing the vendors for each step.

Is it possible to perform all steps from version 4.4 to version 5.4 without updating vendors and then update vendors when my project is in version 5.4?

Thanks in advance for the help

**Comment by TomasVotruba** [comment]
Hi,

the best practise is to go minor version by minor version, e.. 4.4 to 5.0, then 5.0 to 5.1 etc. 
The vendor must be always in functional state, to provide existing and real API of 3rd party packages that you use.

I wrote more about it here: https://tomasvotruba.com/blog/2019/02/28/how-to-upgrade-symfony-2-8-to-3-4/

**Comment by Garfield-fr** [comment]
Hi,

Thank you for this answer.

One more question: If I am upgrading from 4.4 to 5.0, should I update the vendors to 5.0 before running the rector command to upgrade to 5.0?

**Comment by TomasVotruba** [comment]
The current class must exist, so always run with current vendor, and update it after the Rector upgrade.
