### ISSUE TITLE
Cannot autowire service since version 0.11.0/0.11.1

### ISSUE THREAD

**Issue by veelkoov** [rectorphp/rector-symfony#14]
If I missed something, please accept my apologies. I've just upgraded rector and installed rector-symfony and it failed, so I created a simple composer project to test that; below are my findings.

For each version of `composer.json` below, I'm simply running the command `vendor/bin/rector`

This `composer.json` works properly:
```
{
    "require-dev": {
        "rector/rector": "0.10.20",
        "rector/rector-symfony": "0.10.6"
    },
    "require": {}
}

```

---

This one:
```
{
    "require-dev": {
        "rector/rector": "0.11.0",
        "rector/rector-symfony": "0.11.0"
    },
    "require": {}
}
```
throws this error:
> PHP Warning:  include(/.../test/vendor/rector/rector/vendor/composer/../nette/utils/src/Utils/Strings.php): Failed to open stream: No such file or directory in /.../test/vendor/rector/rector/vendor/composer/ClassLoader.php on line 478
> Warning: include(/.../test/vendor/rector/rector/vendor/composer/../nette/utils/src/Utils/Strings.php): Failed to open stream: No such file or directory in /.../test/vendor/rector/rector/vendor/composer/ClassLoader.php on line 478
> PHP Warning:  include(): Failed opening '/.../test/vendor/rector/rector/vendor/composer/../nette/utils/src/Utils/Strings.php' for inclusion (include_path='.:') in /.../test/vendor/rector/rector/vendor/composer/ClassLoader.php on line 478
> Warning: include(): Failed opening '/.../test/vendor/rector/rector/vendor/composer/../nette/utils/src/Utils/Strings.php' for inclusion (include_path='.:') in /.../test/vendor/rector/rector/vendor/composer/ClassLoader.php on line 478
>                                                                                  
>  [ERROR] Class "RectorPrefix20210513\Nette\Utils\Strings" not found
---
And this one (including all later versions if I remember correctly):
```
{
    "require-dev": {
        "rector/rector": "0.11.1",
        "rector/rector-symfony": "0.11.1"
    },
    "require": {}
}
```
throws this:
>  [ERROR] Cannot autowire service "Rector\Symfony\Composer\ComposerNamespaceMatcher": argument "$smartFileSystem" of method "__construct()" has type "Symplify\SmartFileSystem\SmartFileSystem" but this class was not found.

Similar issue may be affecting Doctrine and PHPUnit subrepos.

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting this.
At the moment Rector 0.11 is including the extension in the main release version.

It helps with prefixed and downgraded version and save people from installing 7 Rector package to use it.

Saying that, if you have `rector/rector` installed, you're good to go 👍

**Comment by veelkoov** [comment]
Thank you for explaining!
Yeah, I see now, when and why I got confused.
