### ISSUE TITLE
The getContainer method on the Kernel should not be refractored to DependencyInjection

### ISSUE THREAD

**Issue by alexander-schranz** [rectorphp/rector-symfony#157]
In most cases it make sense that rector is refractoring getContainer calls to dependency injection.

But if the class which is refractored is from class `Symfony\Component\HttpKernel\Kernel` it should be kept that way. I think the there is already an exception for this rule added for KernelTestCase. The Kernel class should also be added as exception for this.

Example: https://github.com/sulu/sulu/blob/e9c3de51ecaca82fb728535c12ec822840922e02/src/Sulu/Bundle/AudienceTargetingBundle/Tests/Application/Kernel.php#L35

![Bildschirmfoto 2022-04-26 um 15 42 54](https://user-images.githubusercontent.com/1698337/165313926-57cf326b-f653-4e72-9821-2a6a8835a413.png)

My used `rector.php`:

```php
<?php

declare(strict_types=1);

use Rector\Config\RectorConfig;
use Rector\Core\Configuration\Option;
use Rector\Symfony\Set\SymfonyLevelSetList;

return static function (RectorConfig $rectorConfig): void {
    $parameters = $rectorConfig->parameters();

    $rectorConfig->paths([
        __DIR__ . '/src',
        __DIR__ . '/tests',
    ]);

    $rectorConfig->importNames();
    $parameters->set(Option::IMPORT_SHORT_CLASSES, false);

    $rectorConfig->sets([
        SymfonyLevelSetList::UP_TO_SYMFONY_54,
    ]);

    $parameters->set(
        Option::SYMFONY_CONTAINER_XML_PATH_PARAMETER,
        __DIR__ . '/var/cache/admin/dev/App_KernelDevDebugContainer.xml',
    );
};
```

I also found other classes which requires to still have the `container`:

 - PHPCR Migration: https://github.com/phpcr/phpcr-migrations/blob/master/lib/VersionInterface.php (are not part of dependency services)
 - CompilerPasses: https://github.com/symfony/symfony/blob/6.1/src/Symfony/Component/DependencyInjection/Compiler/CompilerPassInterface.php (are manipulating the container and so need access it)

**Comment by TomasVotruba** [comment]
Hi, thanks for report.
Which single rule is responsible?

**Comment by alexander-schranz** [comment]
I will try to provide a test case. The rule is https://github.com/rectorphp/rector-symfony/blob/main/src/Rector/MethodCall/ContainerGetToConstructorInjectionRector.php

**Comment by TomasVotruba** [comment]
Hi, any update on this one? It seems like autoloading issue.
