### ISSUE TITLE
Feature idea: Add the Symfony\Component\Console\Attribute\AsCommand attribute

### ISSUE THREAD

**Issue by stephanvierkant** [rectorphp/rector-symfony#159]
As of Symfony 6.1, I've got this notification in my logs:

> Since symfony/console 6.1: Relying on the static property "$defaultDescription" for setting a command description is deprecated. Add the "Symfony\Component\Console\Attribute\AsCommand" attribute to the "App\Command\NotificationCommand" class instead.

I'd the great if Rector can refactor commands with `static $defaultName` and `static $defaultDescription`.

**Comment by TomasVotruba** [comment]
Hi, seems useful feature.
Could you send PR proposal to talk over?
