### ISSUE TITLE
SymfonyLevelSetList::UP_TO_SYMFONY_42 BrowserKit crawler method update parsing throws exception

### ISSUE THREAD

**Issue by jrmcpeek** [rectorphp/rector-symfony#160]
When bumping the SymfonyLevelSetList of a legacy application to `UP_TO_SYMFONY_42`, parsing the code resulted in the following exception:

    [ERROR] Could not process "tests/Controller/Test.php" file, due to:                                  
             "System error: "Invalid identifier name "[]""

I've chased that down to the following minimal code that will trigger the failure above:

```php
/** @test */
public function formTest(): void
{
    $client = static::createClient();

    $crawler = $client->request('GET', '/api/path/here');

    $form = $crawler->selectButton('Button Text Here')->form();

    $client->submit($form);

}
```

I've traced that code _triggering_ the behavior as far as https://github.com/rectorphp/rector-symfony/blob/main/config/sets/symfony/symfony42.php#L66

With that knowledge, I modified the code above to the following:

```php
/** @test */
public function formTest(): void
{
    $client = static::createClient();

    $crawler = $client->request('GET', '/api/path/here');

    $form = $crawler->selectButton('Button Text Here')->form();

    $client->submit($form, []);
}
```
Doing so resolves the exception and allows rector to complete analysis of all code; however, it proposes a change incompatible with the function:

```diff
-        $client->submit($form, []);
+        $client->submit($form, [], []);
```

With `symfony/browser-kit` 4.4.37 vendored, the submit function has the following signature:

```php
public function submit(Form $form, array $values = [])
```

Given the above, I can work around this for the time being, but wanted to document this issue I encountered.

**Comment by TomasVotruba** [comment]
Thank you for your report!

We'll need an isolated failing demo link from: http://getrector.org/demo,
that way we can reproduce the bug.

**Comment by jrmcpeek** [comment]
I made a small sample that triggers the rule here: https://getrector.org/demo/d7fcfe0a-2355-4e12-9eef-5fbb622fa7db

However, the _unexpected behavior_ does not occur on the demo site, so there might be more to it.

When I run locally with `--debug` as the error banner recommends, nothing is output. Is a file created somewhere, or is more necessary to get useful information out of that flag?

**Comment by TomasVotruba** [comment]
I see. Is it possible the argument number should be 1 (2nd) instead of 2 (3rd)?

**Comment by jrmcpeek** [comment]
I tested that locally just now and I no longer get the exception, and the modified code changes as:

```diff
-         $client->submit($form);
+        $client->submit($form, []);
```

But given that the submit prototype provides a default empty array for the second parameter, I'm not sure what benefit this change provides, other than a clean rector run of course 😄.

**Comment by TomasVotruba** [comment]
I see :) The config https://github.com/rectorphp/rector-symfony/blob/main/config/sets/symfony/symfony42.php#L63-L65 mentions these 2 commits:

* https://github.com/symfony/symfony/commit/e3aa90f852f69040be19da3d8729cdf02d238ec7
* https://github.com/symfony/symfony/commit/fa2063efe43109aea093d6fbfc12d675dba82146

Now it seems this was not a BC break, so the whole change be removed IMO.

Could you send PR to remove it?

**Comment by TomasVotruba** [comment]
I see :) The config https://github.com/rectorphp/rector-symfony/blob/main/config/sets/symfony/symfony42.php#L63-L65 mentions these 2 commits:

* https://github.com/symfony/symfony/commit/e3aa90f852f69040be19da3d8729cdf02d238ec7
* https://github.com/symfony/symfony/commit/fa2063efe43109aea093d6fbfc12d675dba82146

Now it seems this was not a BC break, so the whole change be removed IMO.

Could you send PR to remove it?

**Comment by jrmcpeek** [comment]
> Could you send PR to remove it?

Submitted
