### ISSUE TITLE
`CountOnNullRector` doesn't resolve console command array input arguments/options

### ISSUE THREAD

**Issue by Blacksmoke16** [rectorphp/rector-symfony#176]
Related to #175 but specific to array based input /arguments/options for console commands.

For example given:
```php
<?php

declare(strict_types=1);

namespace App\Service;

use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use function dump;

#[AsCommand(name: 'test')]
class TestCommand extends Command
{
    public function configure()
    {
        $this
            ->addArgument('vals', InputArgument::OPTIONAL | InputArgument::IS_ARRAY, 'the values to sum');
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        dump(count($input->getArgument('vals')));

        return 0;
    }
}
```
Running this without any arguments prints `0`. But after running rector, it gets re-written to: `dump(is_countable($input->getArgument('vals')) ? count($input->getArgument('vals')) : 0);`.

I would expect it to be able to resolve that it's an array argument and know its value is always an array. It _does_ work if you manually assign it to a variable and type it as an array:

```php
/** @var array $vals */
$vals = $input->getArgument('vals');

dump(count($vals));
```

**Comment by samsonasik** [comment]
Same with https://github.com/rectorphp/rector-symfony/issues/175#issuecomment-1136846414, I think you can `@var` or `$rectorConfig->skip()` it as well as it pointed to `InputInterface`.
