### ISSUE TITLE
[ERROR] Class 'Rector\Arguments\Rector\ClassMethod\ArgumentDefaultValueReplacerRector' not found

### ISSUE THREAD

**Issue by UFTimmy** [rectorphp/rector-symfony#18]
It appears that the class `ArgumentDefaultValueReplacerRector` moved from `Rector\Arguments\Rector\ClassMethod\ArgumentDefaultValueReplacerRector` to `Rector\Arguments\ArgumentDefaultValueReplacer`. However, the old name is still referenced in 3 places in rector-symfony: symfony28, symfony31, and symfony42. It's also used in nette's 30 setlist.

It looks like the class `ArgumentDefaultValueReplacer` also moved, and it's used in symfony28, so there are probably others that have moved, as well. But I can't see those errors until the first one is fixed.

Here's a demo showing the problem:

https://getrector.org/demo/b24fa402-ce3b-4f46-a9f6-3ed93e75d9c8

I am using rector/rector 0.11.20.

**Comment by TomasVotruba** [comment]
Hi, thanks for spotting this. Could you send PR with set update?

**Comment by UFTimmy** [comment]
I would love to if you can tell me how to install the package locally. I am on PHP 7.4 and get the following:

```  Problem 1
    - rector/rector 0.11.20 conflicts with rector/rector-symfony 0.11.1.
    - rector/rector-symfony[0.11.2, ..., 0.11.5] require php >=8.0 -> your php version (7.4.3) does not satisfy that requirement.
    - rector/rector is locked to version 0.11.20 and an update of this package was not requested.
    - Root composer.json requires rector/rector-symfony ^0.11.1 -> satisfiable by rector/rector-symfony[0.11.1, ..., 0.11.5].
```

**Comment by TomasVotruba** [comment]
The PHP 8 is required for development.

**Comment by UFTimmy** [comment]
Makes sense. In that case it may be some time before I can offer a PR.

**Comment by TomasVotruba** [comment]
What OS do you run? On Linux you can install multiple version and then switch between them:

```bash
sudo apt install php7.4 php8.0
sudo update-alternatives --config php
```

I'm not sure PHP is needed to make this change, since it's only a class rename :slightly_smiling_face:

**Comment by UFTimmy** [comment]
I'm on windows, and we will be switching to PHP 8 soon-ish anyway.

I could make this find and replace with a PR, but I believe there will be other classes that also need a find/replace, which I wouldn't be able to find until I can fork the code. I don't want to submit a PR that only fixes some of the issues.

**Comment by andrew-demb** [comment]
@UFTimmy you can use '--ignore-platform-reqs' option for composer install command

https://getcomposer.org/doc/03-cli.md#install-i
