### ISSUE TITLE
FormTypeWithDependencyToOptionsRector.php is ruining form types that are intended to be services

### ISSUE THREAD

**Issue by trsteel88** [rectorphp/rector-symfony#184]
If we're injecting a service into a form type, rector is attempting to rewrite the parameter as an option.

This shouldn't happen because we need a service injected from the container. Is there a reason this is a default rule?

**Comment by TomasVotruba** [comment]
Hi, could you share exact link with your use case?
https://getrector.org/demo

Are you running Symfony 2.8 upgrade on latter versions?

**Comment by trsteel88** [comment]
@TomasVotruba sorry, I'm not sure how to do that in there but here is a codebase example which is having an issue:

https://github.com/trsteel88/rector-test

```
$ ./vendor/bin/rector process
 3/3 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
                                                                                                                        
 [ERROR] Could not process "src/Form/Choice/ApiChoice.php" file, due to:                                                
         "System error: "Look at "Rector\Symfony\Rector\Class_\FormTypeWithDependencyToOptionsRector::refactor()":115"  
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On 
         line: 115     
```
