### ISSUE TITLE
`StringToArrayArgumentProcessRector` doesn't handle `sprintf` command string

### ISSUE THREAD

**Issue by Blacksmoke16** [rectorphp/rector-symfony#188]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/a1df00ad-a417-4342-8040-3d2e0562e70a

```php
<?php

use Symfony\Component\Process\Process;

$command = sprintf("FOO=%s", 10);

$process = new Process($command);
```

### Responsible rules

* `StringToArrayArgumentProcessRector`

## Expected Behavior

Probably would be easiest to skip it, as migrating the `sprintf` call could lead to wrong results and be quite tricky, if not impossible.

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
You can click "Create a Test" button at demo page.

**Comment by samsonasik** [comment]
@TomasVotruba it seems "Create a Test" button pointed to rector-src, it not create on rector-* packages

**Comment by TomasVotruba** [comment]
I see. Could you update it to point to rector-symfony if the rule is in Rector\Symfony namespace? Making it generic

**Comment by samsonasik** [comment]
I will try.

**Comment by samsonasik** [comment]
https://github.com/rectorphp/getrector.org/pull/613

**Comment by samsonasik** [comment]
deployed so "Create a Test" button is now working on rector-symfony

**Comment by TomasVotruba** [comment]
@samsonasik Amazing work, thank you :+1:
