### ISSUE TITLE
[Symfony 2.5] Add addViolationAt() upgrade rule

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector-symfony#210]
Resources

* https://stackoverflow.com/questions/25264922/symfony-2-5-addviolationat-deprecated-use-buildviolation

**Comment by TomasVotruba** [comment]
Hi @samsonasik , could you handle this one? Let me know if you need more examples of before/after.

**Comment by samsonasik** [comment]
@TomasVotruba I will try. It seems needs a dedicated rule as before/after seems different with multiple method calls and re-arrange args.

**Comment by TomasVotruba** [comment]
Yes, the dedicated rule will the best :)
