### ISSUE TITLE
[Symfony 2.7] Add rename rule for "options" and "type" to "entry_options" and "entry_type"

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector-symfony#214]
See https://github.com/symfony/symfony/pull/15025

```diff
$formBuilder
    ->add('name', 'text', array('label' => '...'))
    ->add(...)
    ->add('friends', 'collection', array(
-        'type' => new FriendType(),
+       'entry_type' => new FriendType(),
-        'options' => array(...)
+        'entry_options' => array(...)
    ))
;
```

This rule might be added, but I could not find it here. So please verify if we have it first. If not, it's should a new rule :slightly_smiling_face:

**Comment by TomasVotruba** [comment]
cc @samsonasik

**Comment by samsonasik** [comment]
@TomasVotruba it seems already exists, ref : 

- https://github.com/rectorphp/rector-symfony/blob/main/docs/rector_rules_overview.md#changecollectiontypeoptionnamefromtypetoentrytyperector

It is part of symfony 3.0 config set:

- https://github.com/rectorphp/rector-symfony/blob/8e8149656ac7c675c9b156cf965abb9925cfdbfa/config/sets/symfony/symfony30.php#L41

**Comment by TomasVotruba** [comment]
I see.

Could you move it to Symfony 2.7? It should be there

**Comment by samsonasik** [comment]
Yes https://github.com/rectorphp/rector-symfony/pull/215
