### ISSUE TITLE
Merge SymfonySetList and SymfonyLevelSetList

### ISSUE THREAD

**Issue by alexander-schranz** [rectorphp/rector-symfony#216]
I personally struggle all the time getting the correct import for the `UP_TO_SYMFONY_61` rule sets.
Would find it better if the `SetList` and `LevelSetList` are merged into a single imported file so I find them at the same place. As sometimes I switching from `UP_TO_*` to single version and vise-versa when doing step by step updates, but have then always import the one or the other file make it a better developer experience from my point of view.

**Comment by TomasVotruba** [comment]
How exactly do you use it?

The difference is that `SymfonyLevelSetList` you with single import of the latest version. It includes all the lower versions, up to the specifies one.

**Comment by alexander-schranz** [comment]
@TomasVotruba I understand the differnce. But I would like to not differ between them and put them into the same class as they diff already by the constant name.

Currently everytime I'm switchting between

```php
    $rectorConfig->sets([
        SymfonySetList::SYMFONY_52,
    ]);
```

And:

```php
    $rectorConfig->sets([
        SymfonyLevelSetList::UP_TO_SYMFONY_52
    ]);
```

Then I need to import `SymfonyLevelSetList` or import `SymfonySetList` again which are in my case not needed to have here 2 different classes as unused imports are removed in my case. I'm doing it a lot to debug sometimes what rector is doing and why it is doing. Sometimes to also find bugs and report them.

I know this `SetList` vs `LevelSetList` depend on other packages so it maybe would be better that I had created it in the general repository. I must also say I can never remind the name of `SymfonyLevelSetList` and need to search it up before. So that is also the case why I would prefer it having it in the `SymfonySetList` class all together and only differ by the constant name.

**Comment by TomasVotruba** [comment]
I see the reason now :) it makes sense. The different is already in the constant name.

Could you propose a PR here?

**Comment by alexander-schranz** [comment]
Symfony: https://github.com/rectorphp/rector-symfony/pull/217  
PHPUnit: https://github.com/rectorphp/rector-phpunit/pull/98

**Comment by TomasVotruba** [comment]
See https://github.com/rectorphp/rector-symfony/pull/217#issuecomment-1221315654
