### ISSUE TITLE
Annotation To Attributes : function constant with wrong argument

### ISSUE THREAD

**Issue by kruggs** [rectorphp/rector-symfony#230]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.14.0             |

Hi,

I'm using SensioLab bundle (extra) for our route in controller.
I'm using the annotation @Security for more flexibility.
I'm using php function `constant` as parameter for `is_granted`. With Attribute, it seems we must use `\\\` instead of `\\`  for the fqn of the class + constant
**Note**: It's a bit strange, not sure it's on purpose or a bug but it's working with 3 instead of 2. So Rector should update this argument too.

## Framework/ORM

Symfony 6.1
Doctrine

## Php

php 8.1.9
CentOs stream 8

## My file rector.php

```
return static function (RectorConfig $rectorConfig): void {

    $rectorConfig->paths([
                             __DIR__ . '/src/Controller/ResourcesBrandController.php'
                         ]);

    // Custom Annotation
    $rectorConfig->ruleWithConfiguration(
        AnnotationToAttributeRector::class, [
                                              new AnnotationToAttribute('App\\Service\\PlatformUserActivity\\Mapping\\Annotation\\UserActivityLoggable'),
                                              new AnnotationToAttribute('App\\Service\\PlatformUserActivity\\Mapping\\Annotation\\Versioned'),
                                          ]
    );

    // https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#inlineconstructordefaulttopropertyrector
    $rectorConfig->rule(InlineConstructorDefaultToPropertyRector::class);

    // Add back new line after statement but keep for Class constant and Trait
    $rectorConfig->rule(NewlineAfterStatementCustomRector::class);

    $rectorConfig->sets(
        [
            DoctrineSetList::ANNOTATIONS_TO_ATTRIBUTES,
            DoctrineSetList::GEDMO_ANNOTATIONS_TO_ATTRIBUTES,
            SymfonySetList::ANNOTATIONS_TO_ATTRIBUTES,
            SymfonySetList::SYMFONY_CODE_QUALITY,
            SensiolabsSetList::FRAMEWORK_EXTRA_61,
            LevelSetList::UP_TO_PHP_80
        ]
    );

};
```

## Original code with annotation

```
/**
 * Class ResourcesBrandController
 *
 * @Route("/%route-backend_prefix%/resources/brand")
 * @Security("is_granted('ROLE_GA_BRAND_USER') and is_granted(constant('\\App\\Security\\Voter\\BrandVoter::ACCESS'))")
 */
class ResourcesBrandControllerextends AbstractController
{
```

## Expected Behaviour

```
/**
 * Class ResourcesBrandController
 */
#[Route(path: '/%route-backend_prefix%/resources/brand')]
#[Security("is_granted('ROLE_GA_BRAND_USER') and is_granted(constant('\\\App\\\Security\\\Voter\\\BrandVoter::ACCESS'))")]
class ResourcesBrandController extends AbstractController
{
```

## What rector do

```
/**
 * Class ResourcesBrandController
 */
#[Route(path: '/%route-backend_prefix%/resources/brand')]
#[Security("is_granted('ROLE_GA_BRAND_USER') and is_granted(constant('\\App\\Security\\Voter\\BrandVoter::ACCESS'))")]
class ResourcesBrandController extends AbstractController
{
```

Like that, the ExpressionLanguage try to load a class called `AppSecurityVoterBrandVoter` instead of `\App\Security\Voter\BrandVoter`

**Comment by TomasVotruba** [comment]
Hi, 

please add a test fixture to the annotation to attribute rule.

**Comment by kruggs** [comment]
Hi,

Do you mean that : https://getrector.org/demo/50e8b73b-3e73-4bbe-bd89-f51210ad5cc2 ?
In that example you have both issue (230 and 228)

Thanks

**Comment by TomasVotruba** [comment]
That's a demo, a good start. But the test fixture is specifi file in our test suite.

For this case, it should be added here: https://github.com/rectorphp/rector-src/tree/main/rules-tests/Php80/Rector/Class_/AnnotationToAttributeRector/Fixture

Each case must be separated and minimal as possible, e.g. only the security annotation should be short as:

```php
 * @Security("func('ARGUMENT')")
```

**Comment by kruggs** [comment]
Ok, i create the file for "Security annotation".
Do i need to create a Pull Request ? I never did it in public repository, so if you have any recommendation ?

Thanks

**Comment by TomasVotruba** [comment]
> Do i need to create a Pull Request ? 

Yes. Push to your fork of `rector/rector-src` and then Github will show you option to create pull-request.

**Comment by kruggs** [comment]
Hi, 
I followed the video but i have an issue.
I forked the repo `rector-src`, then, on my local, i created a new branch from (main) master ,then created the new fixture file, `add` `commit`.
When i try to push to the origin, i have `access denied`. (it's trying to push to ` rectorphp/rector-src.git`, instead of my repo, is it normal ?)
Does it mean i can not create new branch and push ? Do i need to do change on main branch ?

Sorry, it's a bit out of the scope but i used to bitbucket for work, not github :(

Thanks

**Comment by TomasVotruba** [comment]
No problem, we'll make it work :)

> it's trying to push to rectorphp/rector-src.git, instead of my repo, is it normal ?

That usually means you've cloned the `rectorphp/rector-src.git` and only then forked it.
You must first fork the repository, then clone your `https://github.com/kruggs/rector-src` locally.

After that, you can push any code to your fork.

**Comment by kruggs** [comment]
Ok, thanks for your help, i appreciate !
I created the PR [(2840)](https://github.com/rectorphp/rector-src/pull/2840)
