### ISSUE TITLE
[Question] Set for the FOSRestBundle?

### ISSUE THREAD

**Issue by wkania** [rectorphp/rector-symfony#241]
This package already has the JMS, so would it be ok to also add a directory for the [FOSRestBundle](https://github.com/FriendsOfSymfony/FOSRestBundle)?
The `fosrest` directory would contain the set for the annotations to attributes. 
If this is ok then I will write the code.
@TomasVotruba

**Comment by 25matt12** [comment]
That would be great !

**Comment by TomasVotruba** [comment]
Of course 👍 feel free so send any PR with fos upgrade sets.

**Comment by wkania** [comment]
I will try to do it this week.
