### ISSUE TITLE
AddRouteAnnotationRector adds @Route when previous annotation is invalid

### ISSUE THREAD

**Issue by javaDeveloperKid** [rectorphp/rector-symfony#247]
Consider this example:
```php
    /**
     * @ParamConverter("param", class="App\MyEntity"))
     * @Route("/some-route", name="some_name")
     */
```
AddRouteAnnotationRector results in:
```php
    /**
     * @ParamConverter("param", class="App\MyEntity"))
     * @Route("/some-route", name="some_name")
     * @Route("/some-route", name="some_name")
     */
```
`@ParamConverter` annotation has a typo - two closing brackets - but controller works just fine. When one bracket is removed then AddRouteAnnotationRector works fine (does not do anything).

**Comment by malteschlueter** [comment]
I wouldn't see this as a bug of Rector or the rule in a direct sense. The exsiting code should already not have a syntax error.

But this is my personal opinion.

Unfortunately, I don't know Rector's claims on how Rector should handle such faulty preconditions.

**Comment by johanadivare** [comment]
Probably because it cant be parsed, i would say if it works for Symfony as a valid converter then we should probably support it with rector? But i'm also no maintainer here

**Comment by TomasVotruba** [comment]
Hi, 

this needs a fix for annotation first, as we handle parser by expected tokens.

``diff
    /**
-     * @ParamConverter("param", class="App\MyEntity"))
+     * @ParamConverter("param", class="App\MyEntity")
```
