### ISSUE TITLE
[WebTestCaseAssertIsSuccessfulRector] doesn't parse constants

### ISSUE THREAD

**Issue by johanadivare** [rectorphp/rector-symfony#250]
See https://getrector.org/demo/709c0cc8-956a-4914-b710-75f09d63a157 i expect constant values to be parse so that the function is refactored same as WebTestCaseAssertResponseCodeRector see https://getrector.org/demo/5003fb0c-4c5b-4ced-9b27-9a2e7123955f

**Comment by JohJohan** [comment]
See https://github.com/rectorphp/rector-symfony/pull/253

**Comment by JohJohan** [comment]
Fixed with https://github.com/rectorphp/rector-symfony/pull/253#event-7549029657
