### ISSUE TITLE
[CommandPropertyToAttributeRector] is not setting all attributes

### ISSUE THREAD

**Issue by johanadivare** [rectorphp/rector-symfony#254]
# Bug Report
CommandPropertyToAttributeRector is not setting `aliases` and `hidden` in `AsCommand` attribute

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/69d11564-5a50-458b-b185-de0c343b416b

```php
<?php

class SunshineCommand extends \Symfony\Component\Console\Command\Command
{
    /** @var string|null */
    public static $defaultName = 'sunshine';

    /** @var string|null */
    public static $defaultDescription = 'Let the sun shine!';
    

    /**
     * {@inheritdoc}
     */
    protected function configure(): void
    {
        $this
            ->setAliases(['sun', 'shine'])
        ;
    }
}
```

### Responsible rules

* `CommandPropertyToAttributeRector`

## Expected Behavior
```php
<?php

#[\Symfony\Component\Console\Attribute\AsCommand('sunshine', 'Let the sun shine!', ['sun', 'shine'], false)
class SunshineCommand extends \Symfony\Component\Console\Command\Command
{
    /**
     * {@inheritdoc}
     */
    protected function configure(): void
    {
    }
}
```

**Comment by johanadivare** [comment]
Maybe a new rule is more appropriate as the `aliases` and `hidden` are not set with properties but set with configure but they are properties in `\Symfony\Component\Console\Command\Command`

**Comment by johanadivare** [comment]
@JohJohan have a look

**Comment by stof** [comment]
Also, the `MakeCommandLazyRector` is not migrating the description to `$defaultDescription` (probably because it is a lot newer than the `$defaultName`) and so it misses it in most cases too.

**Comment by JohJohan** [comment]
@stof this is done with https://github.com/rectorphp/rector-symfony/pull/257 as discussed here https://github.com/rectorphp/rector-symfony/issues/229

**Comment by stof** [comment]
the rector present in that PR is not documented, which is why I missed it

**Comment by JohJohan** [comment]
@stof good point, i created a pull request to add it to the docs: https://github.com/rectorphp/rector-symfony/pull/260

**Comment by johanadivare** [comment]
Wip: https://github.com/rectorphp/rector-symfony/pull/259

**Comment by johanadivare** [comment]
Fixed with https://github.com/rectorphp/rector-symfony/pull/259
