### ISSUE TITLE
What is the proper way of using Symfony rulesets?

### ISSUE THREAD

**Issue by Wirone** [rectorphp/rector-symfony#26]
We have large application based on custom framework, but many of Symfony components are used. Unfortunately those packages are in different versions (from `3.4` to `5.3`). I thought that when I add `SymfonySetList::SYMFONY_44` ruleset all rulesets for previous versions are loaded too, but I took a look at those rulesets and I don't see any connection between them. So I've used `-vvv` and compared applied rules with single ruleset added against configuration with multiple `SymfonySetList::SYMFONY_*` rulesets and it looks like more rules were applied.

What is the recommended flow for such scenario? Because this package's documentation states:

> To add a set to your config, use `Rector\Symfony\Set\SymfonySetList` class and pick _one_ of constants

Thanks in advance 🙂

**Comment by TomasVotruba** [comment]
Hi, thanks for a great question!

Including smaller sets would not allow to use configs one by one, but rather all or nothing. We have a unix phiolosophy = use the smallest function possible and let people pipe them as they need.

I would go one set by another, having one 1 PR per minor version :) 

I wrote about in detail here: https://tomasvotruba.com/blog/2019/02/28/how-to-upgrade-symfony-2-8-to-3-4

:+1:

**Comment by TomasVotruba** [comment]
See Rector's `rector.php`: https://github.com/rectorphp/rector-src/blob/885ef768e50b8ef86bdf2eb99e290f5dccebd8c1/rector.php#L31-L35

When PHP 8.1 is out, we only add this set, upgrade the codebase in 1 PR and keep it there, so Rector upgrades all the future contributions.

**Comment by Wirone** [comment]
Our codebase is so large (20-year old monolith application) that we currently don't refactor whole, but we have Rector as CI job on merge requests as a failure-allowed helper - only changed files are analysed and diff is printed in the job's output, so developer is encouraged to refactor files on which is working on. In fact, I never managed to run full analysis because of time that it needs 😅 

Because of that, it's not possible to introduce those sets one by one because it's a long-term process of refactoring, hence my question.. 🤔 I think I'll go with multiple sets, up to `SymfonySetList::SYMFONY_44` and then we will try to upgrade dependencies to `5.*`. I am not 100% sure if it will work for us (mostly because of components in `3.4` version that should be upgraded first), but worth try 🙂 

Thanks for the response! I'll close this as I think I got what I needed 👍

**Comment by TomasVotruba** [comment]
I see. Thank for explaining on detail.
Personally I never run Rector on whole code base, if it's too large.  I usually start with controllers, then merge it, etc. 

Instead of forcing devs to do machine work, we narrow scope of the machine.

Check the "ONLY" option. It runs rules only on specific directory 👍
