### ISSUE TITLE
[SYMFONY62] Built-in Cache, Security, Template and Doctrine Attributes

### ISSUE THREAD

**Issue by JohJohan** [rectorphp/rector-symfony#264]
In the blog from Symfony https://symfony.com/blog/new-in-symfony-6-2-built-in-cache-security-template-and-doctrine-attributes its explained new attributes are introduced to replace the once from SensioFrameworkExtraBundle.

We need a few changes:
Replace attributes `IsGranted` and `Cache`:
```diff
-use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
+use Symfony\Component\Security\Http\Attribute\IsGranted;
-use Sensio\Bundle\FrameworkExtraBundle\Configuration\Cache;
+use Symfony\Component\HttpKernel\Attribute\Cache;
```

Replace `ParamConverter` with `MapEntity` see:
```diff
-use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
+use Symfony\Bridge\Doctrine\Attribute\MapEntity;

 // ...
-#[ParamConverter('post', options: ['mapping' => ['postSlug' => 'slug']])]
-public function addComment(Request $request, Post $post): Response
+public function addComment(
+    Request $request,
+    #[MapEntity(mapping: ['postSlug' => 'slug'])] Post $post
+): Response
 {
     // ...
 }
``` 

I can pick this up.

**Comment by JohJohan** [comment]
See https://github.com/rectorphp/rector-symfony/pull/265

**Comment by johanadivare** [comment]
Only MapEntity has to be done still

**Comment by stefantalen** [comment]
> Only replace `ParamConverter` with `MapEntity` has to be done still

@johanadivare are you working on this? If not, mind if I give it a try?

**Comment by johanadivare** [comment]
@stefantalen feel free i'm working on https://github.com/rectorphp/rector-symfony/pull/279#issuecomment-1322075398

Dont forget to add the rule to symfony62.php :)

**Comment by stephanvierkant** [comment]
```diff
- #[\Sensio\Bundle\FrameworkExtraBundle\Configuration\Cache(maxage: 120, lastModified: 'entity.getUpdatedAt()', etag: 'entity.getETag()')]
+ #[\Symfony\Component\HttpKernel\Attribute\Cache(maxage: 120, lastModified: 'entity.getUpdatedAt()', etag: 'entity.getETag()')]
public function someAction(Entity $entity) : Response
{
}
```

This used to work, but now it gives an error:

> Variable "entity" is not valid around position 1 for expression `entity.getUpdatedAt()`.

Any idea why this doesn't work? I can dive into it, but maybe someone has already found out why this doesn't work.

**Comment by johanadivare** [comment]
> ```diff
> - #[\Sensio\Bundle\FrameworkExtraBundle\Configuration\Cache(maxage: 120, lastModified: 'entity.getUpdatedAt()', etag: 'entity.getETag()')]
> + #[\Symfony\Component\HttpKernel\Attribute\Cache(maxage: 120, lastModified: 'entity.getUpdatedAt()', etag: 'entity.getETag()')]
> public function someAction(Entity $entity) : Response
> {
> }
> ```
> 
> This used to work, but now it gives an error:
> 
> > Variable "entity" is not valid around position 1 for expression `entity.getUpdatedAt()`.
> 
> Any idea why this doesn't work? I can dive into it, but maybe someone has already found out why this doesn't work.

I dont know there must be a change in functionality i think its best to create a issue on Symfony for that to be handled.

**Comment by stephanvierkant** [comment]
> I dont know there must be a change in functionality i think its best to create a issue on Symfony for that to be handled.

Done! https://github.com/symfony/symfony/issues/48506

**Comment by johanadivare** [comment]
Fixed with https://github.com/rectorphp/rector-symfony/pull/291
