### ISSUE TITLE
Add functionality to add or even remove a bundle from bundles.php

### ISSUE THREAD

**Issue by alexander-schranz** [rectorphp/rector-symfony#272]
Sometimes when we are adding new features in @sulu a new Bundle need to be registered in `config/bundles.php`.

It would be nice if we can cover this also via rector. 

Is there any similar rule yet to manipulate such arrays? I think it maybe can be a little bit complex as bundles.php is not a class: https://github.com/sulu/skeleton/blob/2.5/config/bundles.php

It just a file returning an array of class-string bundles.

**Comment by stefantalen** [comment]
Aren't Composer recipes meant for that purpose?

**Comment by TomasVotruba** [comment]
Hey, so far nothing similar in Rector set. 
Feel free to send such a feature custom rule, when you find a time :+1:
