### ISSUE TITLE
[SYMFONY62]  Simpler Form Rendering

### ISSUE THREAD

**Issue by johanadivare** [rectorphp/rector-symfony#278]
In Symfony 6.2 a simpler way is introduced to render forms: https://symfony.com/blog/new-in-symfony-6-2-dx-improvements#simpler-form-rendering

I suggest we create a rule that removes the function call `->createView()` what do you think?

**Comment by stefantalen** [comment]
Good suggestion 👍 , [Symfony docs](https://symfony.com/doc/6.2/forms.html#rendering-forms) don't mention the `->createView()` anymore either.

I would also include a rule to replace the deprecated `AbstractController->renderForm()` with `AbstractController->render()`?

**Comment by TomasVotruba** [comment]
Thanks for suggestion, they both sounds good 👍 
Go for it :)

**Comment by johanadivare** [comment]
Fixed with https://github.com/rectorphp/rector-symfony/pull/279

**Comment by stollr** [comment]
I'll exclude this rule, because it hides the fact, that the template will handle a FormView and not a Form. This might be surprising for newcomers and I like to be explicit about my code ;-)

**Comment by stefantalen** [comment]
The [Symfony documentation](https://symfony.com/doc/6.2/forms.html#rendering-forms) suggest implementing it this way. I see no reason for excluding, other than personal preference 🙂 

Newcomers should read the documentation to avoid surprises 😬
