### ISSUE TITLE
[6.2] use Symfony\Bundle\SecurityBundle\Security; instead of Symfony\Component\Security\Core\Security;

### ISSUE THREAD

**Issue by 94noni** [rectorphp/rector-symfony#284]
Hi, I would like to contribute for such [Symfony v6.2 deprecation](https://github.com/symfony/symfony/blob/521d210ca16470437e5c5143c80ab1fb3dc40820/src/Symfony/Component/Security/Core/Security.php#L23)

Perhaps in the `SymfonyLevelSetList::UP_TO_SYMFONY_62` ?

```diff

// src/Controller/MyController.php 

- use Symfony\Component\Security\Core\Security;
+ use Symfony\Bundle\SecurityBundle\Security;

 class MyController extends AbstractController 
 {
    public function index(Security $security)
    {
        // ...
    }
 }
```

I do not know if rector-symfony is relevant for this, but I think so that is why I propose
Feel free to close, thanks !

**Comment by TomasVotruba** [comment]
See https://github.com/rectorphp/rector-symfony/pull/285
