### ISSUE TITLE
[SYMFONY53] replace `getCollectionKeyType` and `getCollectionValueType` with `getCollectionKeyTypes` and `getCollectionValueTypes`

### ISSUE THREAD

**Issue by johanadivare** [rectorphp/rector-symfony#288]
Make sure to write a custom rule for this as return type has changed more information can be found on the [symfony pull request](https://github.com/symfony/symfony/pull/39020)

Some more info https://github.com/rectorphp/rector-symfony/pull/283

**Comment by TomasVotruba** [comment]
Finally getting to these issues, thanks for you patience!
These might require quite a refactoring, as single value to multiple values is not A → B refactoring. 

Closing as we can't handle this. Manual work is needed here :)
