### ISSUE TITLE
[SYMFONY62] Replace `supports` with `resolve`

### ISSUE THREAD

**Issue by johanadivare** [rectorphp/rector-symfony#289]
Make sure to write a custom rule for this as return type has changed from `bool` to `array` more information can be found on the [symfony pull request](https://github.com/symfony/symfony/pull/47363)

Some more info https://github.com/rectorphp/rector-symfony/pull/279#discussion_r1029400492 & https://github.com/rectorphp/rector-symfony/pull/287

**Comment by TomasVotruba** [comment]
@johanadivare Thanks for checking :+1: Could you send a rule for this one?
