### ISSUE TITLE
Rector is adding useless cast (int) to Command::Success

### ISSUE THREAD

**Issue by VincentLanglet** [rectorphp/rector-symfony#293]
Hi,

Now https://github.com/rectorphp/rector-symfony/issues/255 is implemented (cc @johanadivare), there is an issue.
I would say it's the rule https://github.com/rectorphp/rector-symfony/blob/main/docs/rector_rules_overview.md#consoleexecutereturnintrector

When running, rector with the `SymfonyLevelSetList::UP_TO_SYMFONY_61`
I get
```
return 0;
```
changed to
```
 return (int) Command::SUCCESS;
```

If I try to change to
```
 return Command::SUCCESS;
```
Running rector give me again
```
 return (int) Command::SUCCESS;
```

I saw you just did a PR https://github.com/rectorphp/rector-symfony/pull/290 @TomasVotruba, dont know if it was for this.

**Comment by stefantalen** [comment]
Looks like a combination of rules, since the [tests](https://github.com/rectorphp/rector-symfony/pull/256/files#diff-6dcce22fe7445f6cfe9680ee4592d57d0d118376b5009b6a9e2cc1ca7f4c864e) are valid and the expected result doesn't show the cast 🙂

**Comment by VincentLanglet** [comment]
I would say it might be a bug with `ConsoleExecuteReturnIntRector` with cast const to int, even if they are already int.

**Comment by stefantalen** [comment]
I think somewhere in between the rules: 
- [`ConsoleExecuteReturnIntRector` return 0](https://getrector.org/demo/4c942cb5-dec7-4546-9b6f-43a4c8ee7c88) 🎉 
- [`ConsoleExecuteReturnIntRector` return constant](https://getrector.org/demo/0e736e5e-3e6a-4ff8-85e5-7f4a56df44b8) 🎉 
- [`CommandConstantReturnCodeRector` return 0](https://getrector.org/demo/31fc4d3c-8223-4f13-a50a-46ef7802984b) 🎉 
- [Combining rules, return 0](https://getrector.org/demo/d80a473b-9201-46a1-bb32-5844bd36927e) 🔥 

cc @JohJohan

**Comment by samsonasik** [comment]
combination between `ConsoleExecuteReturnIntRector` and `CommandConstantReturnCodeRector` seems cause it https://getrector.org/demo/d80a473b-9201-46a1-bb32-5844bd36927e

**Comment by VincentLanglet** [comment]
Btw, I also found another issue with `CommandConstantReturnCodeRector` https://github.com/rectorphp/rector-symfony/issues/295 ^^'

**Comment by samsonasik** [comment]
That's seems due to just changed return expr got `PHPStan\Type\ErrorType`

**Comment by samsonasik** [comment]
@VincentLanglet The better possible solution is to create correct constant

from:

```
        return $this->nodeFactory->createShortClassConstFetch(
            'Command',
            SymfonyCommandConstantMap::RETURN_TO_CONST[$lNumber->value]
        );
```

to:

```
        return $this->nodeFactory->createClassConstFetch(
            'Symfony\Component\Console\Command\Command',
            SymfonyCommandConstantMap::RETURN_TO_CONST[$lNumber->value]
        );
```

**Comment by VincentLanglet** [comment]
I opened https://github.com/rectorphp/rector-symfony/pull/296 then.
