### ISSUE TITLE
[SYMFONY62] Deprecated MessageHandlerInterface and MessageSubscriberInterface

### ISSUE THREAD

**Issue by enumag** [rectorphp/rector-symfony#318]
These interfaces from `symfony/messenger` are deprecated in Symfony 6.2 in favor of the `AsMessageHandler` attribute.

See https://github.com/symfony/symfony/pull/47068

**Comment by johanadivare** [comment]
This should probably be a custom rule as we will be removing a interface with a attribute more info: https://symfony.com/blog/new-in-symfony-5-4-messenger-improvements
