### ISSUE TITLE
TypedPropertyFromStrictSetUpRector and Symfony container

### ISSUE THREAD

**Issue by yguedidi** [rectorphp/rector-symfony#319]
When using TypedPropertyFromStrictSetUpRector, properties in `setUp()` that are set with `static::getContainer()->get('my_service')` are refactored wit `?object` instead of the inferred type of the service

**Comment by johanadivare** [comment]
@yguedidi can you create a minimal reproducer https://getrector.org/demo

**Comment by TomasVotruba** [comment]
Closing for lack of feedback. Demo link is needed :+1:
