### ISSUE TITLE
[SYMFONY43] Replace GetResponseForExceptionEvent::getException to getThrowable

### ISSUE THREAD

**Issue by gander** [rectorphp/rector-symfony#346]
A bit related with #29 

The [symfony43.php](https://github.com/rectorphp/rector-symfony/blob/main/config/sets/symfony/symfony43.php#L26-L37) file has replace this method, but this method is deprecated since Symfony 4.4. There is no `getThrowable` method in version 4.3 yet.

**Comment by TomasVotruba** [comment]
What do you suggest?

**Comment by TomasVotruba** [comment]
That would be perfect :+1:
