### ISSUE TITLE
Symfony DataMapperInterface iterable vs Traversable

### ISSUE THREAD

**Issue by alleknalle** [rectorphp/rector-symfony#352]
Hi there,

Since Symfony 5.3 the `Symfony\Component\Form\DataMapperInterface` uses `\Traversable` instead of `iterable` for `mapFormsToData` and `mapDataToForms` method. See https://github.com/symfony/form/blob/5.2/DataMapperInterface.php and https://github.com/symfony/form/blob/5.3/DataMapperInterface.php
In the configuration of Rector in `config/sets/symfony/symfony50-types.php` it is specified as using `iterable`, but after that there is no update to `\Traversable`.

Could you please add an update for this change in Symfony forms?

**Comment by johanadivare** [comment]
I can confirm this is the case https://github.com/symfony/form/blob/5.2/DataMapperInterface.php has `iterable` @alleknalle you can create pull request for this. Otherwise i can do it

**Comment by alleknalle** [comment]
@johanadivare I've forked this repo and tried to get my fork running locally, but I'm missing a lot of type hints on PHPStan.
Having some issues working that way, but I managed to create a PR, see https://github.com/rectorphp/rector-symfony/pull/358. 
Hope that it's correct this way. I have no clue how to test this as well...

**Comment by johanadivare** [comment]
I see your pull request is merged: https://github.com/rectorphp/rector-symfony/pull/358 good job! You can close this issue.

**Comment by samsonasik** [comment]
Thank you @alleknalle @johanadivare
