### ISSUE TITLE
[Symfony62] Replace Sensio Security

### ISSUE THREAD

**Issue by wkania** [rectorphp/rector-symfony#393]
[sensio-framework-extra-bundle](https://packagist.org/packages/sensio/framework-extra-bundle) is abandoned.
Some attributes have been implemented in Symfony 6.2 and Rector can already refactor code for [them](https://github.com/rectorphp/rector-symfony/pull/265).
But, `Security` attribute will not be [implemented](https://github.com/symfony/symfony/pull/45415#issuecomment-1077625813) in Symfony.  
From what I know about Rector we can't currently make change [from](https://symfony.com/bundles/SensioFrameworkExtraBundle/current/annotations/security.html):
```
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;

class PostController extends Controller
{
    #[Security("is_granted('ROLE_ADMIN') and is_granted('ROLE_FRIENDLY_USER')")]
    public function index()
    {
    }
}
```
[to](https://symfony.com/doc/current/security/expressions.html):
```
use Symfony\Component\ExpressionLanguage\Expression;
use Symfony\Component\Security\Http\Attribute\IsGranted;

class PostController extends Controller
{
    #[IsGranted(new Expression("is_granted('ROLE_ADMIN') and is_granted('ROLE_FRIENDLY_USER')"))]
    public function index()
    {
    }
}
```
This require a new rule, something custom like [this](https://github.com/rectorphp/rector-phpunit/pull/133)?

**Comment by TomasVotruba** [comment]
Yes, this will need a custom rule, to handle the expressions.

**Comment by johanadivare** [comment]
Well its good to have these 2 cases in testfixure

**Comment by pepeh** [comment]
@wkania 
Why not replace
```
#[Security("is_granted('ROLE_FRIENDLY_USER', author'])")]
public function showAction(User $author): Response
```

with
```
#[IsGranted('ROLE_FRIENDLY_USER', 'author')]
public function showAction(User $author): Response
```

**Comment by wkania** [comment]
@pepeh 
Yes, you are right. My example was to simple.
In my opinion, these are the valid cases and probably many [more](https://symfony.com/doc/current/security/expressions.html):
   
    -------------------
    #[Security("is_granted('ROLE_ADMIN')")]
    #[IsGranted('ROLE_ADMIN')]

    -------------------
    #[Security("is_granted('ASSET_EDIT', asset)")]
    #[IsGranted('ASSET_EDIT', 'asset')]

    -------------------
    #[Security("is_granted('ORGANIZATION_VIEW', team.getOrganization())")]
    #[IsGranted(attribute: new Expression("is_granted('ORGANIZATION_VIEW', subject['team'].getOrganization())"), subject: ['team'])]
    // or
    #[IsGranted('ORGANIZATION_VIEW', subject: new Expression('args["team"].getOrganization()'))]

    // This will throw exception
    #[IsGranted('ORGANIZATION_VIEW', 'team.getOrganization')]
    Error: Could not find the subject "team.getOrganization" for the #[IsGranted] attribute. Try adding a "$team.getOrganization" argument to your controller method.

    -------------------
    #[Security("is_granted('ROLE_ADMIN') or type == 'new'")]
    #[IsGranted(attribute: new Expression("is_granted('ROLE_ADMIN') or subject['type'] == 'new'"), subject: ['type'])]

    -------------------
    #[Security("is_granted('ROLE_ADMIN') or asset.getOrganization() == user.getOrganization()")]
    #[IsGranted(attribute: new Expression("is_granted('ROLE_ADMIN') or subject['asset'].getOrganization() == user.getOrganization()"), subject: ['asset'])]
    // user is one of the special variables


Rector could skip everything with "dot", "or" and "and". Those cases are probably to complex to be refactored automatically or with easy set of conditions.

**Comment by TomasVotruba** [comment]
Looking into this...

**Comment by TomasVotruba** [comment]
I've kicked off a rule to handle this: https://github.com/rectorphp/rector-symfony/pull/622

Give it a try and let me know, what are the missed cases :pray: Thanks

**Comment by wkania** [comment]
I tested it and it's a good start. Most code refactored correctly.

Changed
`#[Security("is_granted('ROLE_ADMIN')")]`
to
`#[\Symfony\Component\Security\Http\Attribute\IsGranted(new \Symfony\Component\ExpressionLanguage\Expression("is_granted('ROLE_ADMIN')"))]`
could be
`#[IsGranted('ROLE_SUPER_ADMIN')]`
Probably it would need to detect if there is no **or/and** and the only function is **is_granted**, then it could skip **Expression**.

Changed
`#[Security("is_granted('ORGANIZATION_EDIT', organization)")]`
to
`#[\Symfony\Component\Security\Http\Attribute\IsGranted(new \Symfony\Component\ExpressionLanguage\Expression("is_granted('ORGANIZATION_EDIT', organization)"))]`
The same as above.

Changed
`#[Security("is_granted('ROLE_ADMIN') or user.isInOrganization(organization)")]`
to
`#[\Symfony\Component\Security\Http\Attribute\IsGranted(new \Symfony\Component\ExpressionLanguage\Expression("is_granted('ROLE_ADMIN') or user.isInOrganization(organization)"))]`
should be (no support for attributes)
`#[IsGranted(new Expression("is_granted('ROLE_ADMIN') or user.isInOrganization(subject['organization'])"), ['organization'])]`
Probably it would need to detect attributes inside **()** for methods and then add  **subject**.

Changed
`#[Security("is_granted('ORGANIZATION_EDIT', terms.getOrganization())")]`
to
`#[\Symfony\Component\Security\Http\Attribute\IsGranted(new \Symfony\Component\ExpressionLanguage\Expression("is_granted('ORGANIZATION_EDIT', terms.getOrganization())"))]`
should be 
`#[IsGranted(new Expression("is_granted('ORGANIZATION_EDIT', subject['terms'].getOrganization())"), ['terms'])]`
Probably it would need  to detect word before dot and if it's not one of special words like **user**, then it should be also **subject**.

Thx @TomasVotruba

**Comment by TomasVotruba** [comment]
Thanks for testing 👍 

Could you share these in form of diffs? I'd check how to add support for them

**Comment by wkania** [comment]
Also variables should be in subject.
```
-    #[Security("is_granted('ROLE_ADMIN') or type == 'new'")]
+    #[\Symfony\Component\Security\Http\Attribute\IsGranted(new \Symfony\Component\ExpressionLanguage\Expression("is_granted('ROLE_ADMIN') or subject['type'] == 'new'"), ['type'])]
```

**Comment by TomasVotruba** [comment]
Thanks, I'll look into it :+1:

**Comment by TomasVotruba** [comment]
See https://github.com/rectorphp/rector-symfony/pull/640
