### ISSUE TITLE
SwiftSetBodyToHtmlPlainMethodCallRector example makes use of ->text but inside code it uses ->plain which afaik doesnt exist

### ISSUE THREAD

**Issue by torian257x** [rectorphp/rector-symfony#401]
https://github.com/rectorphp/rector-symfony/blob/3fa995c7677b2ea654e17dc96cfed1a9ed83732b/src/Rector/MethodCall/SwiftSetBodyToHtmlPlainMethodCallRector.php#L86

->plain doesnt exist see https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/Mime/Email.php

->text does

other things seem to be wrong too like still handing second argument.

**Comment by TomasVotruba** [comment]
Hi, thanks for noticing. Could you send a fix to this rule?

**Comment by stefantalen** [comment]
Looks like the initial plan was to replace a `Swift_Message` with an `Email`, but things got misaligned.

The current rule cannot be used for such a replacement because there are more stones to be moved.
```php
<?php

$message = (new Swift_Message())
    ->setSubject('Your subject')
    ->setFrom(['john@doe.com' => 'John Doe'])
    ->setTo(['receiver@domain.org', 'other@domain.org' => 'A name'])
    ->setBody('Here is the message itself')
?>
-----
<?php

$message = (new \Symfony\Component\Mime\Email())
    ->subject('Your subject')
    ->from(new \Symfony\Component\Mime\Address('john@doe.com', 'John Doe'))
    ->to(...['receiver@domain.org', new \Symfony\Component\Mime\Address('other@domain.org', 'A name')])
    ->text('Here is the message itself')
?>
```

**Comment by torian257x** [comment]
yeah... no... swift mailer and symfony mailer are just too incompatible for our project.

attachments etc etc we refactored by hand into a service so we wont have to do this ever again.

**Comment by JohJohan** [comment]
@TomasVotruba i think conclusion is to close this issue

**Comment by TomasVotruba** [comment]
@JohJohan Thanks for update :+1:  Closing then
