### ISSUE TITLE
Convert controller short syntax in YAML route configuration to fully-qualified class::method

### ISSUE THREAD

**Issue by arnaubuch** [rectorphp/rector-symfony#409]
We're performing a migration of an old Symfony project and we need to change all YAML-configured routes from short notation (e.g. `App:Default:index`) to the newer syntax (e.g. `App\Controller\DefaultController::indexAction`), similarly to the [AddRouteAnnotationRector](https://github.com/rectorphp/rector-symfony/blob/main/src/Rector/ClassMethod/AddRouteAnnotationRector.php) rector. The conversion would be trivial with the [ControllerNameParser](https://github.com/symfony/symfony/blob/3.4/src/Symfony/Bundle/FrameworkBundle/Controller/ControllerNameParser.php) (up to Symfony 4.4), but does Rector provide any helpers to modify YAML files?

**Comment by TomasVotruba** [comment]
Hi, Rector is handling only PHP files, except some simple cases like rename class. 

As for YAML configs, migrate to PHP configs first, it will make the upgrade easier.
