### ISSUE TITLE
False positive error when used in projects which don't have PHPUnit installed

### ISSUE THREAD

**Issue by codebymikey** [rectorphp/rector-symfony#43]
[`SimplifyWebTestCaseAssertionsRector`](https://github.com/rectorphp/rector-symfony/blob/f16d737/src/Rector/MethodCall/SimplifyWebTestCaseAssertionsRector.php#L103-L105) throws a false positive while doing the `$classReflection->isSubclassOf('Symfony\\Bundle\\FrameworkBundle\\Test\\WebTestCase')` check if PHPUnit isn't available in the class loader.

A similar issue also occurs in https://github.com/mglaman/phpstan-drupal/issues/215 for reference purposes.

The output from running rector is something along the lines of:
```
 [ERROR] Could not process
         "web/modules/custom/custom_module/src/EventSubscriber/CustomSubscriber.php" file,
         due to:
         "Analyze error: "Class PHPUnit\Framework\TestCase not found.". Include your files in
         "$parameters->set(Option::AUTOLOAD_PATHS, [...]);" in "rector.php" config.
         See https://github.com/rectorphp/rector#configuration".
```

**Comment by TomasVotruba** [comment]
Hi, could you share minimal reproducible repository on Github so we can examine the bug and then verify the fix? 
With Rector 0.12 version at least.

Thank you

**Comment by samsonasik** [comment]
same as I commented at https://github.com/rectorphp/rector-symfony/issues/62#issuecomment-981264391, it may need an BOOTSTRAP_FILES config, `composer dump-autoload -o` command, or need define autoload paths, see the doc https://github.com/rectorphp/rector/blob/main/docs/static_reflection_and_autoload.md#static-reflection-and-autoload

**Comment by codebymikey** [comment]
Hi @TomasVotruba, I haven't been able to set the time aside to create a minimal repo for it. But I believe this behaviour should occur on any project without PHPUnit installed. Most of the dev/CI environments have phpunit installed, so this "bug" has been harder to reproduce.

I think the issue is more to do with the fact that at this point, the package essentially has a soft requirement on phpunit to be installed in order for the scan to work (even though the scanned file itself isn't necessarily a testcase).
My project doesn't use phpunit so the `BOOTSTRAP_FILES` solution probably wouldn't fix it either since there's no path to point it to.

I'm aware the ` $parameters->set(Option::SKIP, [...]);` method is available to skip the false positive, however I believe `$this->isInWebTestCase($node)` should be capable of handling the missing class issue in a more elegant fashion.

**Comment by samsonasik** [comment]
Documentation updated for Class not found troubleshooting by register to `files` config in composer.json https://github.com/rectorphp/rector/blob/main/docs/static_reflection_and_autoload.md#dealing-with-class--was-not-found-while-trying-to-analyse-it
