### ISSUE TITLE
SYMFONY_CONSTRUCTOR_INJECTION blind spot

### ISSUE THREAD

**Issue by Bilge** [rectorphp/rector-symfony#50]
`SYMFONY_CONSTRUCTOR_INJECTION` does not replace occurrences of `$this->container->get('my.service');`.

### Notes
* It *does* work for `$this->get('my.service')` and even `$this->getContainer()->get('my.service')`.
* `$container` is provided by `ContainerAwareTrait`.

**Comment by TomasVotruba** [comment]
Closing for lack of feedback. We're narrowing issues to keep focus on active and engaging contributor to keep project growing. Thank you for understanding.

Feel free to re-open with failing test case.
