### ISSUE TITLE
RouteCollectionBuilderToRoutingConfiguratorRector should not rename `confifgureRoutes` to `configureRouting`

### ISSUE THREAD

**Issue by rimas-kudelis** [rectorphp/rector-symfony#500]
The following fixer:

https://github.com/rectorphp/rector-symfony/blob/a0af12a8d67d0edefe6cffd22cdced62729a1dd9/rules/Symfony51/Rector/ClassMethod/RouteCollectionBuilderToRoutingConfiguratorRector.php#L78-L132

renames the kernel's `configureRoutes()` method to `configureRouting()`. However, it looks like [Symfony didn't rename the method they are looking for](https://github.com/symfony/symfony/blob/6.4/src/Symfony/Bundle/FrameworkBundle/Kernel/MicroKernelTrait.php#L195-L217), so after the fixer fixes the code, this method is no longer being used.

**Comment by rimas-kudelis** [comment]
Also, the fixer doesn't fix any other usages of the `RouteCollectionBuilder` class. For example, if the `configureRoutes()` method passes its `$routes` argument to another method, that other method remains unfixed and still requires an instance of `RouteCollectionBuilder` and not a `RoutingConfigurator`.

Here's an example of such kernel: https://github.com/BitBagCommerce/OpenMarketplace/blob/master/src/Kernel.php.

**Comment by TomasVotruba** [comment]
Hi, could you send a faling test fixture for RouteCollectionBuilderToRoutingConfiguratorRector? That way we'll have it covered and can fix the behavior

**Comment by TomasVotruba** [comment]
I'm looking into this and this change comes only in Symfony 5.1:
https://github.com/symfony/symfony/pull/32937

It should not be used in previous version and could have changed in future versions. If that happened and Rector missed this change, it will require a new rule in particular Rector versoin

**Comment by TomasVotruba** [comment]
To reopen, please send a failing test fixture to RouteCollectionBuilderToRoutingConfiguratorRectorTest so we know exactly what is being changed :)

**Comment by rimas-kudelis** [comment]
> I'm looking into this and this change comes only in Symfony 5.1: [symfony/symfony#32937](https://github.com/symfony/symfony/pull/32937)
> 
> It should not be used in previous version and could have changed in future versions. If that happened and Rector missed this change, it will require a new rule in particular Rector version

Maybe this PR was later reversed? Because even when [looking at this file in 5.1 branch](https://github.com/symfony/symfony/blob/5.1/src/Symfony/Bundle/FrameworkBundle/Kernel/MicroKernelTrait.php#L31), I don't see any references to `configureRouting()`, but I definitely see some to `configureRoutes()`. Or am I confusing something?

**Comment by rimas-kudelis** [comment]
In fact, if you look at the [history of this file](https://github.com/symfony/symfony/commits/5.1/src/Symfony/Bundle/FrameworkBundle/Kernel/MicroKernelTrait.php), you'll find that the change you referenced (Nov. 25, 2019) was overwritten a couple weeks later (Dec 13, 2019) and the method name was changed back.

I'm not sure how you decide to write these fixers, but I suppose it would be safer to work on them only when the relevant target branch tags a stable release, and to look at the `UPGRADE-x.y.md` file first.

**Comment by TomasVotruba** [comment]
I see. It's possible this rule was created in that window.  Thanks for investigation :+1: 

Could you send a PR to remove this rule then?

**Comment by rimas-kudelis** [comment]
Please take care of this if you can. :pray: I'm not sure when I would get to this myself.

**Comment by TomasVotruba** [comment]
No worries, I'll check it when I found some time
