### ISSUE TITLE
WebTestCaseAssertResponseCodeRector &&  WebTestCaseAssertIsSuccessfulRector does not handle methods that don't use self::createClient

### ISSUE THREAD

**Issue by Guikingone** [rectorphp/rector-symfony#504]
Hi 👋🏻 

I'm facing a small issue while using the `rules/Symfony43/Rector/MethodCall/WebTestCaseAssertIsSuccessfulRector.php` in a class that extends `WebTestCase` but don't use the `self::createClient()` method, the assertion is changed to `assertResponseStatusCodeSame`, this trigger an error as the response is not created when the method is not used, could it be possible to check if the `createClient` method is used (I didn't find a way to check this in the `refactor` method, if there's a way, I'll be glad to help improve it), if yes, the assertion can be changed, if not, the code should stay as it.

Thanks again for the feedback and have a great day 🙂

**Comment by TomasVotruba** [comment]
Closing for lack of feedback. Thanks for understanding :+1:
