### ISSUE TITLE
How I am supossed to use this package?

### ISSUE THREAD

**Issue by playmono** [rectorphp/rector-symfony#506]
Documentation is outdated, this package is not coming with `rector/rector` anymore. So when I'm trying to install both packages:
> composer require rector/rector rector/rector-symfony --dev

These versions are installed:
> Using version ^0.10.6 for rector/rector-symfony
> Using version ^0.10.12 for rector/rector

And when trying
> composer require rector/rector:0.17.* rector/rector-symfony --dev

This is the outcome:
>     - rector/rector[0.17.0, ..., 0.17.1] conflict with rector/rector-symfony 0.16.1.
>     - rector/rector[0.17.0, ..., 0.17.1] conflict with rector/rector-symfony 0.14.2.
>     - rector/rector[0.17.0, ..., 0.17.1] conflict with rector/rector-symfony 0.13.0.
>     - rector/rector[0.17.0, ..., 0.17.1] conflict with rector/rector-symfony 0.12.1.
>     - rector/rector[0.17.0, ..., 0.17.1] conflict with rector/rector-symfony 0.11.48.
>     - rector/rector[0.17.0, ..., 0.17.1] conflict with rector/rector-symfony 0.11.47.
>     - rector/rector[0.17.0, ..., 0.17.1] conflict with rector/rector-symfony 0.11.44.

So, as my composer says, this package and `rector/rector` are incompatible from a long time ago. So then, my question is, how I am supposed to install and use this package?

Thanks.

PS. Dont forget to update the documentation. Thanks.

**Comment by samsonasik** [comment]
It is documented already https://github.com/rectorphp/rector-symfony#install

```
composer require rector/rector --dev
```

You don't install `rector-symfony` is included in scoped vendor:

https://github.com/rectorphp/rector/tree/dde9963adf47455a35aecffcfcba73c935db0180/vendor/rector/rector-symfony

**Comment by playmono** [comment]
Yes, you are right.

The confusion came because VS Code shows as incorrect the namespace import and I assumed that the package wasn't installed.

Thank you.
