### ISSUE TITLE
Router service is replaced with incorrect interface

### ISSUE THREAD

**Issue by Bilge** [rectorphp/rector-symfony#51]
`SYMFONY_CONSTRUCTOR_INJECTION` replaces occurrences of `$this->get('router')` with `ServiceSubscriberInterface` instead of `RouterInterface`.

**Comment by Bilge** [comment]
Obviously it would be fairly short-sighted to just special-case this one particular occurrence, but I think it points to a larger problem with the inadequacy of this fixer. In particular, I notice the following undesirable behaviours: Rector prefers to inject a less derived type than the one being fetched, e.g. interfaces and abstract classes, even when the less derived type does not even exist as a service.

I think it would be prudent to:
* Inject the same service as the one being fetched in the case that the service name matches an existing class name.
* Use the most derived types (leaf type) if such service definition exists.
* Only use interface and abstract types if none of the above applies, and such service definition exists for that type.

**Comment by TomasVotruba** [comment]
Hi, the current context is as simple as your describe.
To improve the type resolving, well have to give Rector more context. 

There could be simple constant map to pick the better type.

**Comment by TomasVotruba** [comment]
Closing for lack of feedback. We're narrowing issues to keep focus on active and engaging contributor to keep project growing. Thank you for understanding.

Feel free to re-open with failing test case.
