### ISSUE TITLE
ActionSuffixRemoverRector should not replace getAction to get

### ISSUE THREAD

**Issue by stollr** [rectorphp/rector-symfony#510]
The current behavior leads to TypeErrors if the controller extends Symfony's `AbstractController` which has a `get` method to load services from the container.

Here's an example error message:
> Compile Error: Declaration of App\Controller\Api\RuleController::get(App\Entity\Rule\Rule $rule): Symfony\Component\HttpFoundation\Response must be compatible with Symfony\Bundle\FrameworkBundle\Controller\AbstractController::get(string $id): object

**Comment by stefantalen** [comment]
Thanks for reporting!

This should only be an issue with Symfony < 6.0.

Any thoughts on a solution?

**Comment by stollr** [comment]
I am unfamiliar with the PHP parser. Is it possible to get all existing methods of the constructor class and its parent classes? Or can reflection be used during refactoring?

**Comment by TomasVotruba** [comment]
Hi @samsonasik , could you fix this one to keep `getAction` as it is? It will break, as `get` is a method from abstract controller.

 Thanks :+1:

**Comment by samsonasik** [comment]
I will try
