### ISSUE TITLE
Symfony 7 rector rule collection

### ISSUE THREAD

**Issue by alexander-schranz** [rectorphp/rector-symfony#537]
I just want to create this issue to collect upgrade rule ideas I stumble over when working on supporting Symfony 7 for some packages.

- [x] classes implementing `Symfony\Component\Form\DataTransformerInterface` requires return types

```diff
-    public function transform($document)
+    public function transform($document): ?string

-    public function reverseTransform($uuid)
+    public function reverseTransform($uuid): ?object
```

----

to be continued ...

----

The question mostly will be should they already be part of the 6.4 Symfony ruleset. When used by a library it could something like adding a return type be a backwards compatibility break. But when used in a project it would not hurt to have the required return types already there, so not sure how this is currently handled by rector rulesets.

**Comment by stefantalen** [comment]
Looking at the current sets (5.0 and 6.0), there a separate sets (`config/sets/symfony/symfony50-types.php` and `config/sets/symfony/symfony6/symfony-return-types.php`) with the type changes which is imported in the actual version set.

Not sure with the reasoning behind it, but probably for cleaner sets. 🙂

**Comment by aragon999** [comment]
Something I just noticed when upgrading a project to Symfony 7, was that `Symfony\Component\Routing\Annotation\Route` -> `Symfony\Component\Routing\Attribute\Route`.

Not sure if this should be contained in the Symfony 6.4 set or Symfony 7 set.

**Comment by samsonasik** [comment]
Its already in symfony 6.4 set, see PR:

- https://github.com/rectorphp/rector-symfony/pull/557

Try latest rector/rector:dev-main

**Comment by aragon999** [comment]
Thank you :-)

**Comment by TomasVotruba** [comment]
I'm looking into this...

**Comment by TomasVotruba** [comment]
@alexander-schranz Thanks for kick of :)

The data transformer return types added in https://github.com/rectorphp/rector-symfony/pull/624

> The question mostly will be should they already be part of the 6.4 Symfony ruleset. When used by a library it could something like adding a return type be a backwards compatibility break.

This is the best choice, as Symfony would add types already in latest major version, 6.4, so extending would comply already with Symfony 6.4 :+1:

**Comment by TomasVotruba** [comment]
> Not sure with the reasoning behind it, but probably for cleaner sets. 🙂

Indeed, there were so many changes in Symfony 5.0 we decided to separate a new set. Just to have better control over changed during an upgrade :)

Return type changes in 6.4 are actually quite few, so we can have it in one set.

**Comment by TomasVotruba** [comment]
Closing as everything mentioned is added now.
If you find something new, let us know in a new issue with before/after code example,
so we can cover it :muscle:
