### ISSUE TITLE
[Downgrade] New rule to handle attribute Symfony Command to Symfony 

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector-symfony#555]
Since Symfony 7.0, downgrade of Rector and any other tool keeps breaking as command name is missing. Symfony 7 handles it by attribute-only, that is not available on PHP 7.4 and bellow.

There should be command that find these attributes and add `setName()` call to a `configure()` method.

## Before:

https://github.com/symfony/console/blob/7.0/Command/CompleteCommand.php#L32C1-L33C44

## After:

```php
public function configure() : void
{
      $this->setName('complete');
}
```

Should be located in `rules/DowngradeSymfony70`. Not neccesary to create a set at the moment, as there only single rule.

**Comment by TomasVotruba** [comment]
@samsonasik Could you look into this one? We'll need it for Rector/ECS and all other symfony/console projects

**Comment by samsonasik** [comment]
I will try, is underscore removed? should the `_complete` changed to `complete`

**Comment by TomasVotruba** [comment]
Not sure, I think it can be removed :+1:

**Comment by samsonasik** [comment]
I mean, naming conversion, looking at the doc, it seems kept, so the new code seems should be:

```diff
-$this->setName('complete');
+$this->setName('|_complete');
```

but I probably missing something

**Comment by TomasVotruba** [comment]
@samsonasik  Okay, let's try it. I think the `|_` is some internal Symfony convention
