### ISSUE TITLE
GetRequestRector blindly stubs any method called getRequest, even if it's not a controller class

### ISSUE THREAD

**Issue by Bilge** [rectorphp/rector-symfony#58]
In my home-brewed API client class, that is just a stand-alone class with no inheritance whatsoever, `GetRequestRector` decides to replace `$this->getRequest()` calls anyway, despite such a method not returning a Symfony Request object.

```diff
class MyClass {
-    public function createSandbox()
+    public function createSandbox(\Symfony\Component\HttpFoundation\Request $request)
     {
         $tempClientId = $this->clientId;

@@ @@

         $this->clientId = 'clients';

-        $request = $this->getRequest(
-            '/',
-            [
-            'ClientId' => 'foo',
-            'Name'     => 'bar',
-            'Email'    => 'baz',
-            ],
-            HttpRequestInterface::METHOD_POST,
-            false
-        );
+        $request = $request;
    }
}
```

It seems to me that, in order for such a substitution to be a valid candidate, the class must extend the Symfony base controller class to implement a version of `$this->getRequest()` that is compatible with this replacement, and Rector should be checking that.

**Comment by TomasVotruba** [comment]
Thanks for the bug reporting.

Could you add failing fixture to the rule so we have it covered? 
Basically same code pasted here: https://github.com/rectorphp/rector-symfony/tree/main/tests/Rector/ClassMethod/GetRequestRector/Fixture
