### ISSUE TITLE
Updated for rector 1+

### ISSUE THREAD

**Issue by nurikabe** [rectorphp/rector-symfony#597]
Running into some unexpected class name errors when trying to run a sf6 upgrade. Should I be using the previous version of Rector?

**Comment by samsonasik** [comment]
Hi, could you create simple reproducible repo? Thank you.

**Comment by samsonasik** [comment]
I am closing it as no reproducible code/config provided.

Tip: For framework upgrade, you can run once, and remove from the set list, see blog post

https://getrector.com/blog/5-common-mistakes-in-rector-config-and-how-to-avoid-them

 then you can upgrade to v1.
