### ISSUE TITLE
GetParameterToConstructorInjectionRector does not handle Commands

### ISSUE THREAD

**Issue by Bilge** [rectorphp/rector-symfony#60]
It seems `GetParameterToConstructorInjectionRector` is hard-coded to only deal with Controllers (of type `Controller` or `AbstractController`), but there once existed [`ContainerAwareCommand`](https://github.com/symfony/symfony/commit/744bf0e7ac3ecf240d0bf055cc58f881bb0b3ec0) also, for which parameter injections may also be needed, in older code bases.

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting. Could you extend the rule to handle other types too?

**Comment by TomasVotruba** [comment]
Closing as there is no `getParameter()` in `ContainerAwareCommand` - https://github.com/symfony/symfony/commit/744bf0e7ac3ecf240d0bf055cc58f881bb0b3ec0
