### ISSUE TITLE
[Symfony 7.0] Add AsDoctrineListener rule

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector-symfony#625]
See https://github.com/symfony/symfony/blob/7.0/UPGRADE-7.0.md#doctrinebridge

**Comment by MrYamous** [comment]
This case seems to be covered by rector-doctrine : https://github.com/rectorphp/rector-doctrine/blob/main/docs/rector_rules_overview.md#eventsubscriberinterfacetoattributerector
