### ISSUE TITLE
[Symfony 7.0] Add AsMessageHandler

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector-symfony#626]
See https://github.com/symfony/symfony/blob/7.0/UPGRADE-7.0.md#messenger

**Comment by stefantalen** [comment]
Isn't this already covered in the [6.2 Setlist](https://github.com/rectorphp/rector-symfony/blob/main/config/sets/symfony/symfony62.php)? 🙃

**Comment by TomasVotruba** [comment]
I've used "AsMessageHandler" to search, but see it now :laughing: thanks :+1:
