### ISSUE TITLE
StringToArrayArgumentProcessRector with $process->setInput()

### ISSUE THREAD

**Issue by refsz** [rectorphp/rector-symfony#646]
I have the following Code in my project:

` $process = new Process($command);
if (\in_array('pandoc', $command, true)) {
  $process->setInput('<p></p>');
}` 

The rule StringToArrayArgumentProcessRector changes the code for setInput to
`$process->setInput(['<p></p>']);`

Then PHPStan complains because setInput does not support arrays.

Should setInput be included in EXCLUDED_PROCESS_METHOD_CALLS?

**Comment by samsonasik** [comment]
Could you provide a patch? the steps:

- add failing fixture into https://github.com/rectorphp/rector-symfony/tree/main/rules-tests/Symfony42/Rector/New_/StringToArrayArgumentProcessRector/Fixture , better add `@see` reference to symfony that pass array is invalid
- provide a patch

thank you.
