### ISSUE TITLE
Please clarify if both xml & php versions of the container need to be configured

### ISSUE THREAD

**Issue by kgilden** [rectorphp/rector-symfony#667]
Hi there,

The following is not quite obvious from the readme.

If I have configured rector with the actual container (via `withSymfonyContainerPhp`), do I still need to specify the path for the xml definition (via `withSymfonyContainerXml`)? In other words, does `withSymfonyContainerPhp` also cover all of the use cases where `withSymfonyConatinerXml` would be needed?

**Comment by TomasVotruba** [comment]
Hey, great questoin - it's always the one that fits your Symfony version. 

They changed dumped format once, so we added support for both.
