### ISSUE TITLE
use Rector\Symfony\Set\SymfonyLevelSetList; [ERROR] How to update Symfony now?

### ISSUE THREAD

**Issue by querty888** [rectorphp/rector-symfony#693]
I want to update Symfony C version 5.2 to version 7.2

I installed rector 1.2

I write in rector.php

use Rector\Symfony\Set\SymfonyLevelSetList;
use Rector\Symfony\Set\SymfonySetList;
I get an error
[ERROR] Class "Rector\Symfony\Set\SymfonyLevelSetList" not found

I try to install composer require rector/rector-symfony

There is a conflict about incompatibility of versions, how to update? Is there a guide?

**Comment by querty888** [comment]
SymfonyLevelSetList::UP_TO_SYMFONY_72, write this and make error

  [ERROR] Class "SymfonyLevelSetList" not found

**Comment by stefantalen** [comment]
UP_TO set lists are deprecated for performance reasons (https://github.com/rectorphp/rector-symfony/pull/572) and have been removed (https://github.com/rectorphp/rector-symfony/pull/609)
