### ISSUE TITLE
Symfony 51 rector rule incorrectly rewrites Responses 

### ISSUE THREAD

**Issue by fvozar** [rectorphp/rector-symfony#73]
Hi Tomas,

I'm working on upgrading Symfony 4.4 application to 5.3 and I'm using your amazing tool to help me with that process. However, I encountered an incorrect change of code for the static `Response::create()` method to `new Response()` in one of the rules.

Here is original code:
```php
class TestController extends AbstractController
{
	public function someAction(): JsonResponse
	{
		return JsonResponse::create(['data' => '...'], Response::HTTP_OK);
	}
}
```

Rector configuration (using version ^0.12.5):
```php
return static function (ContainerConfigurator $containerConfigurator): void {
	// get parameters
	$parameters = $containerConfigurator->parameters();
	$parameters->set(Option::PATHS, [
		__DIR__ . '/src',
	]);

	$parameters->set(Option::BOOTSTRAP_FILES, [
		__DIR__ . '/vendor/autoload.php'
	]);

	$containerConfigurator->import(SymfonyLevelSetList::UP_TO_SYMFONY_51);
};
```

Here is the result after running rector:
```
1) src/Controller/TestController.php:10

    ---------- begin diff ----------
@@ @@

        public function someAction(): JsonResponse
        {
-               return JsonResponse::create(['data' => '...'], Response::HTTP_OK);
+               return new \Symfony\Component\HttpFoundation\JsonResponse();
        }
 }
    ----------- end diff -----------

Applied rules:
 * StaticCallToNewRector (https://github.com/symfony/symfony/pull/35308)
```

I think that the rule should preserve the arguments of the `create()` method when refactoring to the new form to avoid breaking app logic.

A minimum working repository is here: https://github.com/fvozar/rector-symfony-response-rector-bug

**Comment by TomasVotruba** [comment]
Hi, thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
You can click "Create a Test" button at demo page - https://getrector.org/demo

**Comment by fvozar** [comment]
Thanks for the quick response! 

Here is the link https://getrector.org/demo/1ec4df24-0291-65ee-8763-0f2f5d9422c1, but there is an error saying

`Rector could not run due to error: Undefined constant Rector\Symfony\Set\SymfonySetList::SYMFONY_51`

**Comment by TomasVotruba** [comment]
That's probably because there is old version of Rector.
Could you create test fixture manually and send PR to responsible rule in the meantime?

**Comment by fvozar** [comment]
Pull request is ready. Is this what should have I done? Sorry, it's my first contribution here

**Comment by TomasVotruba** [comment]
Yes, that's great, thanks :+1:
