### ISSUE TITLE
Inheritance issue with MakeCommandLazyRector rule

### ISSUE THREAD

**Issue by JorgeHRJ** [rectorphp/rector-symfony#90]
Hi,
I am using the tool in one Symfony project I have and I having this issue:
I have an abstract class which is extending the Command class (`Symfony\Component\Console\Command\Command`). It is like this:

```php
abstract class AbstractExampleCommand extends Command
{
    public function __construct(private string $foo)
    {
        parent::__construct();
    }
}
```

Then I have my command class, which is extending the one explained before. It is like this:

```php
class MyCommand extends AbstractCommand
{
    protected static $defaultName = 'app:command';
    
    public function __construct(string $foo)
    {
        parent::__construct($foo);
    }
}
```
And the Rector tool is suggesting me the following fix:

```bash
    ---------- begin diff ----------
@@ @@

 class MyCommand extends AbstractCommand
 {
+    protected static $defaultName = $foo;
     protected static $defaultName = 'app:command';

     public function __construct(
@@ @@
         string $foo
     ) {
-        parent::__construct($foo);
+        parent::__construct();
     }

     protected function execute(InputInterface $input, OutputInterface $output): int
    ----------- end diff -----------

Applied rules:
 * MakeCommandLazyRector
```

I think it is checking the constructor from the Symfony command class in some way and this is a wrong behavior.
I hope this helps.

**Comment by TomasVotruba** [comment]
Hi thanks for reporting 👍 

Could you add your use case to `MakeCommandLazyRectorTest` in fixture directory, so we have it covered?
Thank you
